import MainLayout from "@/components/layout";
import { cn } from "@/lib/utils";
import { Chakra_Petch } from "next/font/google";
import "./globals.css";

const chakraPetch = Chakra_Petch({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "AI final project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(chakraPetch.className, "")}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
